export const SubCalendarOptions = [
    {text: 'Academic Calendar', value: 'Academic Calendar'},
    {text: 'ASEP Calendar', value: 'ASEP Calendar'},
    {text: 'Chapel', value: 'Chapel'},
    {text: 'Command Group Calendar', value: 'Command Group Calendar'},
    {text: 'Community Relations', value: 'Community Relations'},
    {text: 'Complemenary Events', value: 'Complemenary Events'},
    {text: 'CSL Calendar', value: 'CSL Calendar'},
    {text: 'Garrison Calendar', value: 'Garrison Calendar'},
    {text: 'General Interest', value: 'General Interest'},
    {text: 'Holiday Calendar', value: 'Holiday Calendar'},
    {text: 'PKSOI Calendar', value: 'PKSOI Calendar'},
    {text: 'Social Events And Ceremonies', value: 'Social Events And Ceremonies'},
    {text: 'SSI And USAWC Press Calendar', value: 'SSI And USAWC Press Calendar'},
    {text: 'SSL Calendar', value: 'SSL Calendar'},
    {text: 'Training And Misc Events', value: 'Training And Misc Events'},
    {text: 'USAHEC Calendar', value: 'USAHEC Calendar'},
    {text: 'USAHEC Facilities Usage Calendar', value: 'USAHEC Facilities Usage Calendar'},
    {text: 'Visits And Tours', value: 'Visits And Tours'},
    {text: 'Weekly Pocket Calendar', value: 'Weekly Pocket Calendar'},
]