export const SubCalendarOptions = [
    {text: 'Academic Calendar', value: 'Academic Calendar', email: ''},
    {text: 'ASEP Calendar', value: 'ASEP Calendar', email: ''},
    {text: 'Chapel', value: 'Chapel', email: ''},
    {text: 'Command Group Calendar', value: 'Command Group Calendar', email: ''},
    {text: 'Community Relations', value: 'Community Relations', email: ''},
    {text: 'Complemenary Events', value: 'Complemenary Events', email: ''},
    {text: 'CSL Calendar', value: 'CSL Calendar', email: 'CSLCalendar@hossrob.onmicrosoft.com'},
    {text: 'Garrison Calendar', value: 'Garrison Calendar', email: ''},
    {text: 'General Interest', value: 'General Interest', email: ''},
    {text: 'Holiday Calendar', value: 'Holiday Calendar', email: ''},
    {text: 'PKSOI Calendar', value: 'PKSOI Calendar', email: ''},
    {text: 'Social Events And Ceremonies', value: 'Social Events And Ceremonies', email: ''},
    {text: 'SSI And USAWC Press Calendar', value: 'SSI And USAWC Press Calendar', email: ''},
    {text: 'SSL Calendar', value: 'SSL Calendar', email: ''},
    {text: 'Training And Misc Events', value: 'Training And Misc Events', email: ''},
    {text: 'USAHEC Calendar', value: 'USAHEC Calendar', email: ''},
    {text: 'USAHEC Facilities Usage Calendar', value: 'USAHEC Facilities Usage Calendar', email: ''},
    {text: 'Visits And Tours', value: 'Visits And Tours', email: ''},
    {text: 'Weekly Pocket Calendar', value: 'Weekly Pocket Calendar', email: ''},
]