using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Application.ImportLegacyData
{
    public static class RoomData
    {
        public static Dictionary<string, Dictionary<string, string>> Data = new Dictionary<string, Dictionary<string, string>>()
    {
     
     {"Bldg 46, Anne Ely Hall - CPAC Classroom, Rm 202 ", new Dictionary<string, string>() { {"Email", "AnneElyHallCPACClassroomRm202@armywarcollege.edu"}, {"OldDisplayName", "Anne Ely Hall - CPAC Classroom - Bldg 46, Rm 202 (VTC)"} } },
    {"Bldg 314, Armstrong Hall - G8 Conf Rm ", new Dictionary<string, string>() { {"Email", "ArmstrongHallG8ConfRm@armywarcollege.edu"}, {"OldDisplayName", "Armstrong Hall - G8 Conf Rm - Bldg 314, Conf Rm (VTC)"} } },
    {"Bldg 315 - Old G3 Conference Room, Rm 204A ", new Dictionary<string, string>() { {"Email", "Bldg315OldG3ConferenceRoom@armywarcollege.edu"}, {"OldDisplayName", "Bldg 315, G3 Conference Room"} } },
    {"Bldg 632 - G3 Conference Rm, Rm 130   ", new Dictionary<string, string>() { {"Email", "Bldg632G3ConferenceRm@armywarcollege.edu"}, {"OldDisplayName", ""} } },
    {"Bldg 632 - ASEP Classroom, Rm 112     ", new Dictionary<string, string>() { {"Email", "Bldg632ASEPClassroomRm112@armywarcollege.edu"}, {"OldDisplayName", ""} } },
    {"Bldg 632 - ASEP Conference Rm, Rm 118 ", new Dictionary<string, string>() { {"Email", "Bldg632ASEPConferenceRmRm118@armywarcollege.edu"}, {"OldDisplayName", ""} } },
    {"Bldg 632 - G3 SIPR Room, Rm 136", new Dictionary<string, string>() { {"Email", "Bldg632G3SIPRRoomRm136@armywarcollege.edu"}, {"OldDisplayName", ""} } },
    {"Bliss Hall - Auditorium", new Dictionary<string, string>() { {"Email", "BlissHallAuditorium@armywarcollege.edu"}, {"OldDisplayName", "Bliss Hall - Auditorium (VTC)"} } },
    {"Bliss Hall - Foyer", new Dictionary<string, string>() { {"Email", "BlissHallFoyer@armywarcollege.edu"}, {"OldDisplayName", "Bliss Hall - Foyer"} } },
    {"Bldg 650, Collins Hall - B037 (SVTC)", new Dictionary<string, string>() { {"Email", "Bldg650CollinsHallB037SVTC@armywarcollege.edu"}, {"OldDisplayName", "Collins Hall - Rm B037 (VTC)"} } },
    {"Bldg 650, Collins Hall - Normandy Conference Room (SVTC)", new Dictionary<string, string>() { {"Email", "Bldg650CollinsHallNormandyConferenceRoomSVTC@armywarcollege.edu"}, {"OldDisplayName", "Collins Hall - Normandy Conf Rm (MCR), Rm 3008 (VTC)"} } },
    {"Bldg 650, Collins Hall - Toy Room, Rm 1018", new Dictionary<string, string>() { {"Email", "Bldg650CollinsHallToyRoomRm1018@armywarcollege.edu"}, {"OldDisplayName", "Collins Hall - Toy Room, Bldg 650, Rm 1018 (VTC)"} } },
{"Bldg 650, Collins Hall - Jayhawk Lounge, Rm 1028", new Dictionary<string, string>() { {"Email", "Bldg650CollinsHallJayhawkLoungeRm1028@armywarcollege.edu"}, {"OldDisplayName", "Collins Hall - Jayhawk Lounge, Bldg 650, Rm 1028"} } },
{"Bldg 650, Collins Hall - St. Lo. Room, Rm 3006 (SVTC)", new Dictionary<string, string>() { {"Email", "Bldg650CollinsHallStLoRoomRm3006@armywarcollege.edu"}, {"OldDisplayName", "Collins Hall - St. Lo. - Bldg 650, Rm 3006 (VTC)"} } },
{"Bldg 650, Collins Hall - Guadalcanal Room, Rm. 3013", new Dictionary<string, string>() { {"Email", "Bldg650CollinsHallGuadalcanalRoomRm3013@armywarcollege.edu"}, {"OldDisplayName", "Collins Hall - Guadalcanal Room - Bldg 560, Rm 3013"} } },
{"Bldg 650, Collins Hall - B030", new Dictionary<string, string>() { {"Email", "Bldg650CollinsHallB030@armywarcollege.edu"}, {"OldDisplayName", "Collins Hall - Rm B030 (VTC)"} } },
{"Bldg 650, Collins Hall - B033A (SVTC)", new Dictionary<string, string>() { {"Email", "Bldg650CollinsHallB033ASVTC@armywarcollege.edu"}, {"OldDisplayName", "Collins Hall - Rm B033A (VTC)"} } },
{"Bldg 650, Collins Hall - Media Room", new Dictionary<string, string>() { {"Email", "Bldg650CollinsHallMediaRoom@armywarcollege.edu"}, {"OldDisplayName", "Collins Hall - B038/Media Room"} } },
{"Bldg 650, Collins Hall - Ardennes Room (Cafeteria)", new Dictionary<string, string>() { {"Email", "Bldg650CollinsHallArdennesRoomCafeteria@armywarcollege.edu"}, {"OldDisplayName", "Collins Hall - Ardennes Room, Bldg 650, Rm B059"} } },
{"Bldg 650, Collins Hall - 18th Inf Conference Room", new Dictionary<string, string>() { {"Email", "Bldg650CollinsHall18thInfConferenceRoom@armywarcollege.edu"}, {"OldDisplayName", "Collins Hall - 18th Inf Conf Room (VTC)"} } },
{"Bldg 650, Collins Hall - 22nd Inf Conference Room (SVTC)", new Dictionary<string, string>() { {"Email", "Bldg650CollinsHall22ndInfConferenceRoomSVTC@armywarcollege.edu"}, {"OldDisplayName", "Collins Hall - 22nd Inf Conf Room (VTC)"} } },
{"Bldg 650, Collins Hall - Cherbourg Room, Rm 1015", new Dictionary<string, string>() { {"Email", "Bldg650CollinsHallCherbourgRoomRm1015@armywarcollege.edu"}, {"OldDisplayName", "Collins Hall - Cherbourg Room, Bldg 650, Rm 1015 (VTC)"} } },
{"Bldg 650, Collins Hall - BSAP Conference Room (SVTC)", new Dictionary<string, string>() { {"Email", "Bldg650CollinsHallBSAPConferenceRoomSVTC@armywarcollege.edu"}, {"OldDisplayName", "Collins Hall - BSAP Conf Rm, B047, Bldg 650, Rm B047"} } },
{"Bldg 650, Collins Hall - Aachen Room (SVTC)", new Dictionary<string, string>() { {"Email", "Bldg650CollinsHallAachenRoomSVTC@armywarcollege.edu"}, {"OldDisplayName", "Collins Hall - Aachen Rm, Main VTC Suite, Rm 1030 (VTC)"} } },
{"Bldg 650, Collins Hall - CSL Zoom.gov", new Dictionary<string, string>() { {"Email", "Bldg650CollinsHallCSLZoomgov@armywarcollege.edu"}, {"OldDisplayName", "Collins Hall - CSL Zoom.gov Virtual Meeting"} } },
{"Bldg 650, Collins Hall - TEST ROOM", new Dictionary<string, string>() { {"Email", "Bldg650CollinsHallTESTROOM@armywarcollege.edu"}, {"OldDisplayName", "Collins Hall - TEST ROOM , Bldg 650 (VTC)"} } },
{"Bldg 650, Collins Hall - TEST ROOM 2", new Dictionary<string, string>() { {"Email", "Bldg650CollinsHallTESTROOM2@armywarcollege.edu"}, {"OldDisplayName", "Collins Hall - TEST ROOM 2, Bldg 650 (VTC)"} } },
{"Bldg 22, Upton Hall - Upton Auditorium", new Dictionary<string, string>() { {"Email", "UptonAuditorium@armywarcollege.edu"}, {"OldDisplayName", "Upton Hall - Upton Auditorium - Bldg 22"} } },
{"Bldg 22, Upton Hall - Bradley Auditorium", new Dictionary<string, string>() { {"Email", "Bldg22UptonHallBradleyAuditorium@armywarcollege.edu"}, {"OldDisplayName", "Upton Hall - Bradley Auditorium, Bldg 22"} } },
{"Bldg 22, Upton Hall - PKSOI Conference Room", new Dictionary<string, string>() { {"Email", "Bldg22UptonHallPKSOIConferenceRoom@armywarcollege.edu"}, {"OldDisplayName", "Upton Hall PKSOI - Bldg 22, Rm 200A (VTC)"} } },
{"Bldg 22, Upton Hall - Garrison Commander Conf Rm, Rm 201", new Dictionary<string, string>() { {"Email", "Bldg22UptonHallGarrisonCommanderConfRmRm201@armywarcollege.edu"}, {"OldDisplayName", "Upton Hall - Garrison Cdr Conf - Bldg 22, Rm 117A (VTC)"} } },
{"Reynolds Theater", new Dictionary<string, string>() { {"Email", "ReynoldsTheater@armywarcollege.edu"}, {"OldDisplayName", "Reynolds Theater"} } },
{"Bldg 47, SSI - Conference Room, Rm 119", new Dictionary<string, string>() { {"Email", "Bldg47SSIConferenceRoomRm119@armywarcollege.edu"}, {"OldDisplayName", "SSI - Conf Rm - Bldg 47, Rm 119 (VTC)"} } },
{"Bldg 950, Ridgway Hall - Meeting Room, Rm 130", new Dictionary<string, string>() { {"Email", "RidgwayRidgwayHallMeetingRoomRm127@armywarcollege.edu"}, {"OldDisplayName", "USAHEC - Ridgway Hall, Meeting Room (Max 8)"} } },
{"Bldg 950, Ridgway Hall - Ridgway Conference Rm, Rm 210", new Dictionary<string, string>() { {"Email", "Bldg950RidgwayHallRidgwayConferenceRoomRm210@armywarcollege.edu"}, {"OldDisplayName", "USAHEC - Ridgway Hall, Conference Room (Max 30)"} } },
{"Bldg 950, Ridgway Hall - Pre-Function Hallway 1, Rm 309", new Dictionary<string, string>() { {"Email", "Bldg950RidgwayHallPreFunctionHallway1Rm309@armywarcollege.edu"}, {"OldDisplayName", "USAHEC - VEC, Pre-Function Hallway 1"} } },
{"Bldg 950, Ridgway Hall - Multipurpose Room 1, Rm 311", new Dictionary<string, string>() { {"Email", "Bldg950RidgwayHallMultipurposeRoom1Rm311@armywarcollege.edu"}, {"OldDisplayName", "USAHEC - VEC, Multipurpose Room 1 (Max 120) (VTC)"} } },
{"Bldg 950, Ridgway Hall - Multipurpose Room 2, Rm 312", new Dictionary<string, string>() { {"Email", "Bldg950RidgwayHallMultipurposeRoom2Rm312@armywarcollege.edu"}, {"OldDisplayName", "USAHEC - VEC, Multipurpose Room 2 (VTC) (Max 120)"} } },
{"Bldg 950, Ridgway Hall - Command Conference Room, Rm 338", new Dictionary<string, string>() { {"Email", "Bldg950RidgwayHallCommandConferenceRoomRm338@armywarcollege.edu"}, {"OldDisplayName", "USAHEC - VEC, Command Conference Room (VTC) (Max 15)"} } },
{"Bldg 950, Ridgway Hall - Multipurpose Room 3, Rm 367", new Dictionary<string, string>() { {"Email", "Bldg950RidgwayHallMultipurposeRoom3Rm367@armywarcollege.edu"}, {"OldDisplayName", "USAHEC - VEC, Multipurpose Room 3 (Max 50)"} } },
{"Bldg 950, Ridgway Hall - Multipurpose Room 4, Rm 368", new Dictionary<string, string>() { {"Email", "Bldg950RidgwayHallMultipurposeRoom4Rm368@armywarcollege.edu"}, {"OldDisplayName", "USAHEC - VEC, Multipurpose Room 4 (Max 50)"} } },
{"Bldg 950, Ridgway Hall - Pre-Function Hallway 2, Rm 374", new Dictionary<string, string>() { {"Email", "Bldg950RidgwayHallPreFunctionHallway2Rm374@armywarcollege.edu"}, {"OldDisplayName", "USAHEC - VEC, Pre-Function Hallway 2"} } },
{"Bldg 950, Ridgway Hall - Quanset Hut Pavilion", new Dictionary<string, string>() { {"Email", "Bldg950RidgwayHallQuansetHutPavilion@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 122, Root Hall - Mary Walker Rm", new Dictionary<string, string>() { {"Email", "mary.walker@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - Dr. Mary E. Walker Room - Bldg 122, Rm B110 (VTC)"} } },
{"Bldg 122, Root Hall - Command Conference Room", new Dictionary<string, string>() { {"Email", "ccr@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - CCR, Bldg 122"} } },
{"Bldg 122, Root Hall - One Button Studio", new Dictionary<string, string>() { {"Email", "one.button@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 122, Root Hall - Will Washcoe Auditorium", new Dictionary<string, string>() { {"Email", "will.washcoe@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - Wil Washcoe Auditorium, Bldg 122 (VTC)"} } },
{"Bldg 122, Root Hall - Experimental Classroom", new Dictionary<string, string>() { {"Email", "experimental.classroom@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - Experimental Classroom"} } },
{"Bldg 122, Root Hall - SIPR Cafe, Rm SB19", new Dictionary<string, string>() { {"Email", "Bldg122RootHallSIPRCafeRmSB19@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - SIPR Café - Bldg 122, Rm SB19"} } },
{"Bldg 122, Root Hall - B026, The ACL Lab Classroom", new Dictionary<string, string>() { {"Email", "Bldg122RootHallB026TheACLLabClassroom@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - ACL Lab B26  - Root Hall Basement - Bldg 122, Rm B26"} } },
{"Bldg 122, Root Hall - A201", new Dictionary<string, string>() { {"Email", "Bldg122RootHallA201@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - Rm A201"} } },
{"Bldg 122, Root Hall - A205, Seminar 21", new Dictionary<string, string>() { {"Email", "Bldg122RootHallA205Seminar21@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - A205 SG21"} } },
{"Bldg 122, Root Hall - A221, Seminar 23", new Dictionary<string, string>() { {"Email", "Bldg122RootHallA221Seminar23@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - A221 SG23"} } },
{"Bldg 122, Root Hall - A225, Seminar 20", new Dictionary<string, string>() { {"Email", "Bldg122RootHallA225Seminar20@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - A225 SG20"} } },
{"Bldg 122, Root Hall - A232, Seminar 22", new Dictionary<string, string>() { {"Email", "Bldg122RootHallA232Seminar22@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - A232 SG22"} } },
{"Bldg 122, Root Hall - A301, Seminar 6", new Dictionary<string, string>() { {"Email", "Bldg122RootHallA301Seminar6@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - A301 SG6"} } },
{"Bldg 122, Root Hall - A305, Seminar 5", new Dictionary<string, string>() { {"Email", "Bldg122RootHallA305Seminar5@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - A305 SG5"} } },
{"Bldg 122, Root Hall - A325, Seminar 8", new Dictionary<string, string>() { {"Email", "Bldg122RootHallA325Seminar8@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - A325 SG8"} } },
{"Bldg 122, Root Hall - B323, Seminar 9", new Dictionary<string, string>() { {"Email", "Bldg122RootHallA323Seminar9@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - B323 SG9"} } },
{"Bldg 122, Root Hall - A329, Seminar 7", new Dictionary<string, string>() { {"Email", "Bldg122RootHallA329Seminar7@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - A329 SG7"} } },
{"Bldg 122, Root Hall - B203, Seminar 18", new Dictionary<string, string>() { {"Email", "Bldg122RootHallB203Seminar18@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - B203 SG18"} } },
{"Bldg 122, Root Hall - B207, Seminar 17", new Dictionary<string, string>() { {"Email", "Bldg122RootHallB207Seminar17@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - B207 SG17"} } },
{"Bldg 122, Root Hall - Otto Chaney Room, B216, Seminar 24", new Dictionary<string, string>() { {"Email", "Bldg122RootHallOttoChaneyRoomB216Seminar24@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - Otto Chaney Room, Bldg 122, Rm B216 (VTC)"} } },
{"Bldg 122, Root Hall - B219, Seminar 19", new Dictionary<string, string>() { {"Email", "Bldg122RootHallB219Seminar9@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - B219 SG19"} } },
{"Bldg 122, Root Hall - B303, Seminar 4", new Dictionary<string, string>() { {"Email", "Bldg122RootHall303Seminar4@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - B303 SG4"} } },
{"Bldg 122, Root Hall - Colonel Ted D. Cordrey Room, DDE", new Dictionary<string, string>() { {"Email", "Bldg122RootHallColonelTedDCordreyRoomDDE@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - Colonel Ted D. Cordrey Room, (DDE) Rm B305"} } },
{"Bldg 122, Root Hall - B307, Seminar 3", new Dictionary<string, string>() { {"Email", "Bldg122RootHallB307Seminar3@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - B307 SG3"} } },
{"Bldg 122, Root Hall - B319, Seminar 10", new Dictionary<string, string>() { {"Email", "Bldg122RootHallB319Seminar10@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - B319 SG10"} } },
{"Bldg 122, Root Hall - Brian Moore Room", new Dictionary<string, string>() { {"Email", "Bldg122RootHallBrianMooreRoom@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - Brian Moore Room, C-129 DMSPO"} } },
{"Bldg 122, Root Hall - DNSS Conf Room", new Dictionary<string, string>() { {"Email", "Bldg122RootHallDNSSConfRoom@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - DNSS Conf Room, Rm C-202"} } },
{"Bldg 122, Root Hall - C207, Seminar 13", new Dictionary<string, string>() { {"Email", "Bldg122RootHallC207Seminar13@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - C207 SG13"} } },
{"Bldg 122, Root Hall - Sara Morgan Conference Room, DCLM", new Dictionary<string, string>() { {"Email", "Bldg122RootHallSaraMorganConferenceRoomDCLM@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - Sara Morgan Conference Room, C331"} } },
{"Bldg 122, Root Hall - C211, Seminar 14", new Dictionary<string, string>() { {"Email", "Bldg122RootHallC211Seminar14@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - C211 SG14"} } },
{"Bldg 122, Root Hall - C229, Seminar 15", new Dictionary<string, string>() { {"Email", "Bldg122RootHallC229Seminar15@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - C229 SG15"} } },
{"Bldg 122, Root Hall - C233, Seminar 16", new Dictionary<string, string>() { {"Email", "Bldg122RootHallC233Seminar16@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - C233 SG16"} } },
{"Bldg 122, Root Hall - C307, Seminar 2", new Dictionary<string, string>() { {"Email", "Bldg122RootBldg122RootHallC307Seminar2@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - C307 SG2"} } },
{"Bldg 122, Root Hall - C311, Seminar 1", new Dictionary<string, string>() { {"Email", "Bldg122RootHallC311Seminar1@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - C311 SG1"} } },
{"Bldg 122, Root Hall - C329, Seminar 12", new Dictionary<string, string>() { {"Email", "Bldg122RootHallC329Seminar12@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - C329 SG12"} } },
{"Bldg 122, Root Hall - C333, Seminar 11", new Dictionary<string, string>() { {"Email", "Bldg122RootHallC333Seminar11@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - C333 SG11"} } },
{"Bldg 122, Root Hall - DCLM Conference Room, Rm C337", new Dictionary<string, string>() { {"Email", "Bldg122RootHallDCLMConferenceRoomRmC337@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - DCLM Conference Room, C337"} } },
{"Bldg 122, Root Hall - SB015", new Dictionary<string, string>() { {"Email", "Bldg122RootHallSB015@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - SB 15"} } },
{"Bldg 122, Root Hall - Study Room, Rm SB06", new Dictionary<string, string>() { {"Email", "Bldg122RootHallStudyRoomRmSB06@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - SB06 Study Room"} } },
{"Bldg 122, Root Hall - Study Room, Rm SB07", new Dictionary<string, string>() { {"Email", "Bldg122RootHallStudyRoomRmSB07@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - SB07 Study Room"} } },
{"Bldg 122, Root Hall - Study Room, Rm SB08", new Dictionary<string, string>() { {"Email", "Bldg122RootHallStudyRoomRmSB08@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - SB08 Study Room"} } },
{"Bldg 122, Root Hall - Study Room, Rm SB09", new Dictionary<string, string>() { {"Email", "Bldg122RootHallStudyRoomRmSB09@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - SB09 Study Room"} } },
{"Bldg 122, Root Hall - SB24", new Dictionary<string, string>() { {"Email", "Bldg122RootHallSB24@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - CEC SB24 - Root Hall Basement - Bldg 122, Rm SB24"} } },
{"Bldg 122, Root Hall - Library Breakout A", new Dictionary<string, string>() { {"Email", "Bldg122RootHallLibraryBreakoutA@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - Library Breakout A"} } },
{"Bldg 122, Root Hall - Library Breakout B", new Dictionary<string, string>() { {"Email", "Bldg122RootHallLibraryBreakoutB@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - Library Breakout B"} } },
{"Bldg 122, Root Hall - Library Breakout C", new Dictionary<string, string>() { {"Email", "Bldg122RootHallLibraryBreakoutC@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - Library Breakout C"} } },
{"Bldg 122, Root Hall - Library Breakout D", new Dictionary<string, string>() { {"Email", "Bldg122RootHallLibraryBreakoutD@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - Library Breakout D"} } },
{"Bldg 122, Root Hall - Library Breakout E", new Dictionary<string, string>() { {"Email", "Bldg122RootHallLibraryBreakoutE@armywarcollege.edu"}, {"OldDisplayName", "Root Hall - Library Breakout E"} } },
{"Bldg 651 - Bliss Auditorium, Rm 146", new Dictionary<string, string>() { {"Email", "Bldg651BlissAuditoriumRm146@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Lecture Hall East - IHOF 1", new Dictionary<string, string>() { {"Email", "Bldg651LectureHallEastIHOF1@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Cafeteria, Rm 037", new Dictionary<string, string>() { {"Email", "Bldg651-CafeteriaRm037@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - The Atrium, Rm 102", new Dictionary<string, string>() { {"Email", "Bldg651TheAtriumRm102@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - I-Hub Cafe, Rm 116", new Dictionary<string, string>() { {"Email", "Bldg651IHubCafeRm116@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Top Floor Knowledge Commons, Rm 130", new Dictionary<string, string>() { {"Email", "Bldg651TopFloorKnowledgeCommonsRm130@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Sky Box North, Rm 142", new Dictionary<string, string>() { {"Email", "Bldg651SkyBoxNorthRm142@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Sky Box South, Rm 143", new Dictionary<string, string>() { {"Email", "Bldg651SkyBoxSouthRm143@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Green Room, Rm 074", new Dictionary<string, string>() { {"Email", "Bldg651GreenRoomRm074@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Lecture Hall Social", new Dictionary<string, string>() { {"Email", "Bldg651LectureHallSocial@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Innovation Hub Laboratory, Rm 114", new Dictionary<string, string>() { {"Email", "Bldg651InnovationHubLaboratoryRm114@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Innovation Hub Collab Center (The Forge) Rm 115", new Dictionary<string, string>() { {"Email", "Bldg651InnovationHubCollaborationCenterTheForgeRm115@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - The Studio, Rm 117", new Dictionary<string, string>() { {"Email", "Bldg651TheStudioRm117@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Learning Lab 1, Rm 120", new Dictionary<string, string>() { {"Email", "Bldg651LearningLab1Rm120@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Learning Lab 2, Rm 121", new Dictionary<string, string>() { {"Email", "Bldg651LearningLab2Rm121@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - ACL Lab Hybrid Space, Rm 122", new Dictionary<string, string>() { {"Email", "Bldg651ACLLabHybridSpaceRm122@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Recording Studio, Rm 078", new Dictionary<string, string>() { {"Email", "Bldg651RecordingStudioRm078@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Pod Cast Room, Rm 082", new Dictionary<string, string>() { {"Email", "Bldg651PodCastRoomRm082@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Co-Lab 2071", new Dictionary<string, string>() { {"Email", "Bldg651CoLab2071@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Central Col-Lab Hall, Rm 2065", new Dictionary<string, string>() { {"Email", "Bldg651CentralColLabHallRm2065@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Co-Lab 2069", new Dictionary<string, string>() { {"Email", "Bldg651CoLab2069@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Co-Lab 2073", new Dictionary<string, string>() { {"Email", "Bldg651CoLab2073@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Co-Lab 3064", new Dictionary<string, string>() { {"Email", "Bldg651CoLab3064@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Co-Lab 3067", new Dictionary<string, string>() { {"Email", "Bldg651CoLab3067@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Co-Lab 3069", new Dictionary<string, string>() { {"Email", "Bldg651CoLab3069@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Co-Lab 3100", new Dictionary<string, string>() { {"Email", "Bldg651CoLab3100@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Co-Lab 3102", new Dictionary<string, string>() { {"Email", "Bldg651CoLab3102@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Co-Lab 3104", new Dictionary<string, string>() { {"Email", "Bldg651CoLab3104@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Co-Lab 3106", new Dictionary<string, string>() { {"Email", "Bldg651CoLab3106@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Collab Room - 034", new Dictionary<string, string>() { {"Email", "Bldg651CollabRoom034@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Collab Room 035", new Dictionary<string, string>() { {"Email", "Bldg651CollabRoom035@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Collab Room 036", new Dictionary<string, string>() { {"Email", "Bldg651CollabRoom036@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Study / Focus Room 136", new Dictionary<string, string>() { {"Email", "Bldg651StudyFocusRoom136@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Study / Focus Room 137", new Dictionary<string, string>() { {"Email", "Bldg651StudyFocusRoom137@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Study / Focus Room 138", new Dictionary<string, string>() { {"Email", "Bldg651StudyFocusRoom138@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - 2nd Floor Central Commons, Rm 2067", new Dictionary<string, string>() { {"Email", "Bldg6512ndFloorCentralCommonsRm2067@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - 2nd Floor West Commons, Rm 2091", new Dictionary<string, string>() { {"Email", "Bldg6512ndFloorWestCommonsRm2091@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - 3rd Floor East Commons, Rm 3022", new Dictionary<string, string>() { {"Email", "Bldg6513rdFloorEastCommonsRm3022@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - 3rd Floor West Commons, Rm 3087", new Dictionary<string, string>() { {"Email", "Bldg6513rdFloorWestCommonsRm3087@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Lecture Hall West - IHOF 2, Rm 148", new Dictionary<string, string>() { {"Email", "Bldg651LectureHallWestIHOF2Rm148@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Mary Walker Room, Rm 041", new Dictionary<string, string>() { {"Email", "Bldg651MaryWalkerRoomRm041@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Command Conference Room (CCR)", new Dictionary<string, string>() { {"Email", "Bldg651CommandConferenceRoomCCR@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Board Room - Otto Chaney Room, Rm 061", new Dictionary<string, string>() { {"Email", "Bldg651BoardRoomOttoChaneyRoomRm061@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Central Medium Collab Rm - Francis DeSario Rm 2064", new Dictionary<string, string>() { {"Email", "Bldg651CentralMediumCollabRmFrancisDeSarioRm2064@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - 2nd Floor Large Conference Room, Rm 2086", new Dictionary<string, string>() { {"Email", "Bldg6512ndFloorLargeConferenceRoomRm2086@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - 3rd Floor Medium Conference Room 3002", new Dictionary<string, string>() { {"Email", "Bldg6513rdFloorMediumConferenceRoom3002@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - 3rd Floor Large Conference Room 3083", new Dictionary<string, string>() { {"Email", "Bldg6513rdFloorLargeConferenceRoom3083@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room 2026", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoom2026@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room - Double, Rm 2031", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoomDoubleRm2031@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room - Double, Rm 2032", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoomDoubleRm2032@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room 2057", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoom2057@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room 2060", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoom2060@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room 2062", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoom2062@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room 2066", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoom2066@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room 2084", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoom2084@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room - Double, Rm 2089", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoomDoubleRm2089@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room - Double, Rm 2090", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoomDoubleRm2090@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room 2099", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoom2099@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room 2107", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoom2107@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room 3018", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoom3018@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room - Double, Rm 3024", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoomDoubleRm3024@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room - Double, Rm 3025", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoomDoubleRm3025@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room 3048", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoom3048@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room 3051", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoom3051@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room 3053", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoom3053@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room 3062", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoom3062@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room 3080", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoom3080@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room - Double, Rm 3085", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoomDoubleRm3085@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room - Double, Rm 3086", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoomDoubleRm3086@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room 3095", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoom3095@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - Seminar Room 3107", new Dictionary<string, string>() { {"Email", "Bldg651SeminarRoom3107@armywarcollege.edu"}, {"OldDisplayName", ""} } },
{"Bldg 651 - 3rd Floor Central Commons, Rm 3063", new Dictionary<string, string>() { {"Email", "Bldg6513rdFloorCentralCommonsRm3063@armywarcollege.edu"}, {"OldDisplayName", ""} } },
    };
    }
}
